---

- hosts: all
  strategy: free
  gather_facts: yes
  become: yes
  vars_prompt:
    - name: username
      private: no
      prompt: "INPUT username"
    - name: "password"
      private: yes
      prompt: "INPUT password"
      encrypt: "sha512_crypt"
      confirm: no
      salt_size: 7
  roles:
   - create-user
